export const GET_VIDEO_START = 'YOUTUBE/GET_VIDEOS_START';
export const GET_VIDEO_SUCCEED = 'YOUTUBE/GET_VIDEOS_SUCCEED';
export const GET_VIDEO_FAIL = 'YOUTUBE/GET_VIDEOS_FAIL';

export const GET_PLAYLIST_START = 'YOUTUBE/GET_PLAYLIST_START';
export const GET_PLAYLIST_SUCCEED = 'YOUTUBE/GET_PLAYLIST_SUCCEED';
export const GET_PLAYLIST_FAIL = 'YOUTUBE/GET_PLAYLIST_FAIL';
